### ISSUE TITLE
using NetworkInference error

### ISSUE THREAD

**Issue by WenduoGu** [Tchanders/NetworkInference.jl#25]
Hi, I used 

Pkg.clone("https://github.com/Tchanders/NetworkInference.jl") 
and 
Pkg.add("NetworkInference") 
for adding the package.

However, when i run

using NetworkInference

the following error occurs.

[ Info: Precompiling NetworkInference [6b44d3db-2bc5-5ac3-b70f-26aa69b1b11b]
ERROR: LoadError: LoadError: LoadError: UndefVarError: @parallel not defined
Stacktrace:
 [1] top-level scope
 [2] include at .\boot.jl:317 [inlined]
 [3] include_relative(::Module, ::String) at .\loading.jl:1044
 [4] include at .\sysimg.jl:29 [inlined]
 [5] include(::String) at C:\Users\Wenduo\.julia\packages\NetworkInference\sbYgY\src\NetworkInference.jl:1
 [6] top-level scope at none:0
 [7] top-level scope at none:2
in expression starting at C:\Users\Wenduo\.julia\packages\NetworkInference\sbYgY\src\network_inference.jl:62
in expression starting at C:\Users\Wenduo\.julia\packages\NetworkInference\sbYgY\src\network_inference.jl:51
in expression starting at C:\Users\Wenduo\.julia\packages\NetworkInference\sbYgY\src\NetworkInference.jl:25
ERROR: Failed to precompile NetworkInference [6b44d3db-2bc5-5ac3-b70f-26aa69b1b11b] to C:\Users\Wenduo\.julia\compiled\v1.0\NetworkInference\WOYob.ji.

Could you help me with the issue?

Thank you & Best Regards
Wendy

**Comment by WenduoGu** [comment]
I also tried to add the package without first cloning it. And the following error occurs.

Pkg.add("NetworkInference")
  Updating registry at `C:\Users\Wenduo\.julia\registries\General`
  Updating git-repo `https://github.com/JuliaRegistries/General.git`
 Resolving package versions...
ERROR: Unsatisfiable requirements detected for package NetworkInference [6b44d3db]:
 NetworkInference [6b44d3db] log:
 ├─possible versions are: 0.0.1 or uninstalled
 ├─restricted to versions * by an explicit requirement, leaving only versions 0.0.1
 └─restricted by julia compatibility requirements to versions: uninstalled — no versions left
Stacktrace:
 [1] top-level scope at none:0

**Comment by Tchanders** [comment]
Hi - thanks for the report. Which version of Julia are you using, so I can investigate?

**Comment by WenduoGu** [comment]
> Hi - thanks for the report. Which version of Julia are you using, so I can investigate?
Thanks for the reply.
I was using Julia 1.0.3 and the error occurred. But I re-installed Julia 0.7.0 and it seemed to be working.

**Comment by Tchanders** [comment]
Thanks for the additional info. The @parallel macro is deprecated in Julia 1.0, we need to use @distributed from the Distributed package to be compatible with 1.0. The REQUIRE file states that this is compatible with 1.0, which isn't the case, so re-opening the issue.
