### ISSUE TITLE
Can I run in parallel?

### ISSUE THREAD

**Issue by BW15061999** [Tchanders/NetworkInference.jl#32]

**Comment by Tchanders** [comment]
If you have multiple processes available, NetworkInference will distribute the most intensive calculations across the processes (the for loops in `get_mi_scores` and `get_puc_scores`). This can speed things up considerably for large datasets. It's worth testing different numbers of processes to work out the optimum speed-up for your datasets and setup.

**Example**

You can open Julia in the command line with 3 extra processes (so 4 in total), then call `infer_network` as usual:

```
$ ./julia -p 3

julia> using NetworkInference

julia> infer_network(<path to data file>, PIDCNetworkInference())
```

There's more about the topic in general here: https://docs.julialang.org/en/v1/manual/distributed-computing/

Thanks for the question - I'll add a note about this to the README.
