### ISSUE TITLE
Question about the edge weight

### ISSUE THREAD

**Issue by dongyuanwu** [Tchanders/NetworkInference.jl#37]
Hi, 

Thanks for this useful package! 

I have a question about the edge weight. According to the document, it is the confidence of the edge existing in the true network. Then does it have a fixed range? I also checked the paper, and it said that c=F_X(u_X,Y)+F_Y(u_X,Y). F is the cumulative distribution. In this way, I think the range of the edge weight should be [0, 2]. It makes me very confused because I got a network that has the edge weights exceed 2.

I built networks for two groups, separately. The edge weights of group 1 are from 0 to 2, whereas the weights of group 2 are from 0 to 10. Is it reasonable or did I make something wrong? If it is reasonable, I would like to know if the edge weights between two groups are comparable. If it is wrong, could you please help me figure out the problem?

Looking forward to your reply and thank you in advance!

**Comment by dongyuanwu** [comment]
Update: I tried to build more networks based on the permuted data sets, the edge weights for all of them were between 0 and 2. Then I noticed that the original one that had values exceeded 2 printed many messages like below:

      From worker 2:	Gamma distribution failed for SDF4 and TNFRSF9; used normal instead.
      From worker 3:	Gamma distribution failed for MTHFD2 and GNLY; used normal instead.
      From worker 4:	Gamma distribution failed for IL21 and SPRY1; used normal instead.
      From worker 5:	Gamma distribution failed for EZR and SOD2; used normal instead.
      From worker 6:	Gamma distribution failed for PABPC1 and AZIN1; used normal instead.

Not sure if it is the issue. But even if we use the normal distribution, the weights should still not exceed 2 because of the property of the cumulative distribution function.

**Comment by Tchanders** [comment]
Hi, thanks for the question! The PIDC algorithm should give edge weights in the range [0, 2], but the other algorithms may not. It's true that Gamma/Normal distributions shouldn't affect this.

Would it be possible to share the code you're using to get the edge weights?

**Comment by dongyuanwu** [comment]
Sure! The code is below. And I have attached the data I used
[healthy_norm.txt](https://github.com/Tchanders/NetworkInference.jl/files/6469051/healthy_norm.txt)

```
using NetworkInference
nodes = get_nodes("/.../healthy_norm.txt")
inferred_network = InferredNetwork(PIDCNetworkInference(), nodes)
write_network_file("/.../healthy_norm_pidc.txt", inferred_network)
```

More information I noticed: The data set contains 2 genes that did not express in any cells, after removing them, the largest edge weight will change from ~10 to ~4.5. It also contains 2 genes that expressed in an extremely small number of cells (< 1% of cells), after removing them, the edge weights will be in the range [0, 2].

**Comment by anncfs** [comment]
This is rather late now, but I came across similar situations. It happens when a gene shows no expression (or very low expression in just a few cells) resulting in all zeros in the discretised data. The gamma fit fails (as per the error message) and defaults to the normal distribution. However, this then calculates weights using the CLR weight calculation (which is NOT a sum of two probabilities, but a sum of scaled differences from the means of the normal distributions). As a result, the weights can exceed 2 for the CLR weights and the PIDC / CLR weights are not comparable. I'd suggest removing any genes with zero or very low expression and repeating the inference to ensure the Gamma distribution works for all of them.
